pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=test  # Ensure CI passes
      - base=main  # Only merge to main branch
    actions:
      merge:
        method: squash