[package]
name = "zefiro-pipeline"
version = "0.0.0-pre"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
petgraph = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
zefiro-cwl = { version = "0.0.0-pre", path = "../zefiro-cwl" }
zefiro-job = { version = "0.0.0-pre", path = "../zefiro-job" }
async-nats = { workspace = true }
k8s-openapi = { workspace = true }
kube = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
tokio-stream = { workspace = true }
serde = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }