[package]
name = "zefiro-cwl-parser"
version = "0.1.0"
description = """
"The Common Workflow Language (CWL) object model that used in `zefiro`.
"""
authors = [
  "Nikita Syzrantsev <syzrantsev.n@gmail.com>"
]
categories = ["CWL serialization", "CWL deserialization", "Common Workflow Language"]
keywords = ["CWL", "CommandLineTool", "Workflow"]
edition = "2021"
homepage = "https://github.com/zefiroproj/zefiro"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/zefiroproj/zefiro"
rust-version = "1.83.0"

[dependencies]
anyhow = "1.0.95"
serde = { version = "1.0.216", features = ["derive"] }
serde_with = "3.12.0"
serde_yaml = "0.9.34"

[dev-dependencies]
rstest = "0.24.0"
tempfile = "3.15.0"
