[package]
name = "zefiro-cwl-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
serde = { version = "1.0.216", features = ["derive"] }
serde_with = "3.12.0"
serde_yaml = "0.9.34"

[dev-dependencies]
rstest = "0.24.0"
