name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-22.04
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install git-cliff
        uses: orhun/git-cliff-action@v4
        id: git-cliff
      - name: Run git-cliff to generate changelog
        run: git-cliff -vv --latest --no-exec --github-repo ${{ github.repository }} --config cliff.toml
        id: changelog

   publish-crates-io:
   name: Publish on crates.io
   runs-on: ubuntu-22.04
   needs: generate-changelog
   steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Verify package
      run: cargo verify-project
    - name: Run tests
      run: cargo test --all-features
    - name: Set the release version
      run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> "$GITHUB_ENV"
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      uses: dtolnay/rust-toolchain@stable
    # - name: Publish the zefiro-core library
    #   run: |
    #     cargo publish --manifest-path zefiro-core/Cargo.toml \
    #       --locked --token ${{ secrets.CARGO_REGISTRY_TOKEN }}